### PR TITLE
ci: Improve github actions

### LINKED ISSUE #36: Code Coverage
I think it could be useful to run code coverage on this repository, to figure out where tests can be improved :)

@KokaKiwi would have to register on codecov.io or coveralls and the ci would run over the entire repository and list some places, that the tests do not cover. Sometimes it has some mismatches, but it works most of the time.

I would recommend to use https://codecov.io/ in combination with [`cargo tarpaulin`](https://github.com/xd009642/tarpaulin) (tarpaulin is way better, than kcov)

For reference, you can look at this repository
https://github.com/sile/hls_m3u8
and this is the `.travis.yml`
https://github.com/sile/hls_m3u8/blob/master/.travis.yml

The only thing I would change is to add an `--ignore-panics` flag, maybe you could also add caching to improve compilation speed? (the linked .travis.yml has it too).
I would not run this on every target and only on a single one (`stable` or `nightly`, but when you want to include doc examples in the coverage, you have to use nightly)

### PR DESCRIPTION
**Pull request by koushiro**
* Add code format check & clippy check
* Add no_std build
* Add MSRV build
* Add code coverage (Close #36)
* Add more badges

Signed-off-by: koushiro <koushiro.cqx@gmail.com>

### CODE REVIEW

**Comment by koushiro** [comment]
@KokaKiwi PTAL

**Comment by KokaKiwi** [comment]
To be honest, i have a (kinda major) problem with this Pull Request as it sets a MSRV (`hex` doesn't have one, yet): I would prefer this matter to be handled at another "time" (like, on a separate PR), as it would involve some discussions and reflexions about what would be the "best" version to set as MSRV, especially regarding stuff like `const-generic` features.

**Comment by koushiro** [comment]
I just decide the MSRV based on the existing code and features of the hex crate. Of course, you could change it later, as long as it will not cause breaking changes when releasing the new version of the crate.

**Comment by KokaKiwi** [comment]
Yeah, the test+badge could be changed later, but i would actually prefer if this PR did only CI-related changes, as so when `hex` MSRV is set the test+badge would be added at this time, not before :)

**Review by KokaKiwi — APPROVED** [review]

**Pull request merged**
