### PR TITLE
Make `byte2hex` and `val` const functions

### PR DESCRIPTION
**Pull request by Luro02**

### CODE REVIEW

**Comment by KokaKiwi** [comment]
Looking at the changes, i was wondering what would be the effect of making these function `const`, as they are private?

I suppose maybe some inlining and const-propagation stuff, but i'm not sure.

**Comment by Luro02** [comment]
This will most likely have no performance improvements, but clippy will stop complaining about the functions not being constant.

**Comment by KokaKiwi** [comment]
Eh, i didn't know clippy had a lint like that :smile:

**Comment by Luro02** [comment]
> Eh, i didn't event know clippy had a lint like that 😄

By default clippy does not show all lints. You can enable a lot more by adding this to the top of `lib.rs`:

```rust
#![warn(clippy::pedantic, clippy::nursery)]
```

[see table here](https://github.com/rust-lang/rust-clippy#clippy)

**Pull request merged**
