### PR TITLE
API extensions, small API modifications and documentation

### PR DESCRIPTION
**Pull request by LukasKalbertodt**
Hi there!

I wanted to use your crate but noticed that using it is not as easy as it could be. With this PR I try to fix that. The most important changes are:

- I added a `decode()` and `encode()` function. This matches the API of other crates like `base64`. Being able to say `hex::encode("hi")` is pretty nice.
- I added a lot of documentation

For more information on the changes, you can read the commit messages. Please let me know if there's anything you don't like. It would be awesome if this could be merged and published to crates.io.

But note, that this is a **breaking change**. So bump the version to `0.3.0` before publishing :wink:

### CODE REVIEW

**Comment by LukasKalbertodt** [comment]
@KokaKiwi any updates on this? Updates like "I don't have time to review right now" are welcome too ^_^

**Comment by KokaKiwi** [comment]
Sorry yeah,
Well actually, this week I indeed don't have the time to review the current issues/PR ^^

But i'll soon restart working actively on this library (especially because of the Rust libz blitz thing) 🙂

**Comment by Stargateur** [comment]
This pool request look great adding example, documentation and generic.

**Comment by KokaKiwi** [comment]
I think I'll merge this PR and continue some modifications from there, as it seems to me to be a good way to go for this lib :)

**Comment by LukasKalbertodt** [comment]
@KokaKiwi Thanks! If you want me to modify my PR, just go ahead and tell me what you want to be changed. Of course, you can also just do as you said: merge and make changes yourself.

**Comment by LukasKalbertodt** [comment]
@KokaKiwi I'm really not trying to be a pain in the ass... but what about this PR? :) 

Should I change something in this PR still?

**Comment by KokaKiwi** [comment]
Hi, sorry I thought I would have some time to work on this but I'm the worse at time management x)
But I'm gonna merge the PR, then it should be easier for me to plan some time to work on it :)

**Pull request merged**
